### ISSUE TITLE
Soft-code identity url in discussion-rendering according to environment

### ISSUE THREAD

**Issue by ioannakok** [guardian/discussion-rendering#677]
1. A user who does not have a discussion username set
2. Tries to make a comment
3. They're taken to the 'set username' flow
4. When they hit submit, nothing happens on the page, and the POST call to https://idapi.theguardian.com/user/me?api-key=dotcom-rendering fails with a CORS error

![Image](https://user-images.githubusercontent.com/19683595/213485129-2f8415a9-ca8d-4c42-bc20-1c99439878be.png)

5. The payload of that call is the setting of the new username, which means the call to set a new username doesn't work

![Image](https://user-images.githubusercontent.com/19683595/213485215-0b1527d8-1394-408f-8b38-26250048a3c1.png)

**Comment by VDuczekW** [comment]
George and Ioanna are pairing and in flight
