### ISSUE TITLE
Update `discussion-rendering` to use okta tokens

### ISSUE THREAD

**Issue by coldlink** [guardian/discussion-rendering#725]
Discussion rendering is used to render the box which is use to interact with comments as a user, this will need to be updated to accept okta tokens when making calls to discussion api or identity api through this.

This file makes all the requests I think:
https://github.com/guardian/discussion-rendering/blob/main/src/lib/api.tsx

We should pass in the initialised `IdentityAuth` class to discussion-rendering for it to use tokens, instead of it initialising it's own.

**Comment by sunnyclimber456** [comment]
Discussion rendering has moved to https://github.com/guardian/dotcom-rendering/
